# Generated by Django 4.2.7 on 2024-10-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='question_or_topic',
            field=models.CharField(default='no topic provided', help_text='The question or topic of the submission.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='submission_type',
            field=models.CharField(choices=[('article', 'Article'), ('report', 'Report'), ('essay', 'Essay'), ('mcq', 'Multiple Choice')], default='essay', max_length=50),
        ),
    ]
