# Generated by Django 4.2.7 on 2024-11-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradApp', '0003_studentsubmission_submittedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmission',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
